version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=mysql
      - DB_PORT=3307
      - DB_USER=veepearldb
      - DB_PASS=root
      - DB_NAME=veepearl_db
      - DB_HOST=localhost
      - DB_ROOT_PASSWORD=root
    ports:
      - "8082:8082"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mysql
    networks:
      - veepearl-network


  mysql:
    image: mysql:8.0.1
    container_name: veepearlapp
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: veepearl_db
      MYSQL_USER: veepearldb
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - veepearl-network


networks:
  veepearl-network:
    driver: bridge

volumes:
  mysql_data:
